minio:
  endpoint: ""
  accessKeyId: ""
  secretAccessKey: ""
server:
  hostName: ""
  debug: true
  remoteEnable: false
  dataPath: ""
  fileAddress: "0.0.0.0:8009"
  m3u8Address: "0.0.0.0:8008"
  nodes:
    - "https://a01.xx.com/"
    - "https://a01.xx.com/"
    - "https://a01.xx.com"